var dicionario = {
  frases: [
    'Aqui é Body Builder Ipsum PORRA!',
    'É esse que a gente quer, é ele que nóis vamo buscar.',
    'Não vai dá não.',
    'BIIRRRRRRRRLL!!!!',
    'AHHHHHHHHHHHHHHHHHHHHHH..., porra!',
    'Sabe o que é isso daí? Trapézio descendente é o nome disso aí.',
    'Sai filho da puta!',
    'Eu quero esse 13 daqui a pouquinho aí.',
    'É verão o ano todo vem cumpadi.',
    'É 37 anos caralho!',
    'Birl!',
    'É 13 porra!',
    'Bora caralho, você quer ver essa porra velho.',
    'Vamo monstro!',
    'Vai subir árvore é o caralho porra!',
    'Vem porra!',
    'Sai de casa comi pra caralho porra.',
    'Birl!',
    'BIRL!',
    'BIIRRRRRRRRLL!!!',
    'AHHHHHHHHHHHHHHHHHHHHHH..., porra!',
    'Vo derrubar tudo essas árvore do parque ibirapuera.',
    'PORRA',
    'Aqui nóis constrói fibra, não é água com músculo.',
    'Ajuda o maluco que tá doente.',
    'É nóis caraio é trapezera buscando caraio!',
    'Ele tá olhando pra gente.',
    'Birl!',
    'Negativa Bambam negativa.',
    'BIIRRRRRRRRLL!!!!',
    'Boraaa, Hora do Show Porra.',
    'Aqui é bodybuilder porra!',
    'Ó o homem ali porra!',
    'Eita porra!',
    'tá saindo da jaula o monstro!',
    'Tá comigo porra.',
    'BIIRRRRRRRRLL!!!!'
  ]
};

module.exports = dicionario;